name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (release)
        run: swift build -c release

      - name: Test (offline only)
        run: swift test

